# Generated by Django 5.0.6 on 2024-08-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomed', '0003_sitesettings_logo_sitesettings_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
