# Generated by Django 5.0.6 on 2024-08-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomed', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
