# Generated by Django 5.0.6 on 2024-08-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomed', '0007_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='changelog',
            name='object_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
